import type { Metadata } from "next";

import "./globals.css";
import { cn } from "@/utils/cn";
import {Mulish, Roboto} from 'next/font/google' 


import { ToastProvider } from "@/components/ui/toasts/ToastProvider";
import NextToploader from "nextjs-toploader";


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const mulish = Mulish({ // Use the Mulish font
  weight: "variable",
  subsets: ["latin"],
  variable: "--font-mulish",
  display: "swap",
});

const roboto = Roboto({  // Use the Roboto font
  weight: "400",
  subsets: ["latin"],
  variable: "--font-roboto",
  display: "swap",
});


  export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body


    className={cn(
          "antialiased overscroll-none bg background ", roboto.variable, 
          mulish.variable,
        )}
      >   

      

        {children}
        
      </body>
    </html>
  );
}
